services:
  flowsynx.pluginregistry:
    image: ${DOCKER_REGISTRY-}flowsynxpluginregistry
    build:
      context: .
      dockerfile: src/FlowSynx.Pluginregistry/Dockerfile
    container_name: flowsynx-plugin-registry
    ports:
      - "7236:7236"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:${APP_PORT}
      - Endpoint__BaseAddress=${APP_BASEADDRESS}
      - ConnectionStrings__DatabaseConnection=${APP_DB_CONNECTION}
      - Authentication__GitHub__ClientId=${GITHUB_CLIENTID}
      - Authentication__GitHub__ClientSecret=${GITHUB_CLIENTSECRET}
      - Authentication__GitHub__CallbackPath=${GITHUB_CALLBACKPATH}
    volumes:
      - pluginregistry_data:/app/storage
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: fpr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@$$w0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pluginregistry_data: